name: databricks-cicd

on:
 push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # Install databricks CLI 
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh  

      - name: Databricks CLI version
        run: databricks --version
      - name: Run databricks job "pipeline"
        env:
          DATABRICKS_HOST: https://dbc-11df7ca4-5026.cloud.databricks.com
          DATABRICKS_TOKEN: dapi2f98369b849c3790a880a6a9e4748434
          JOB_NAME: 'pipeline'
          WAIT_TIMEOUT: '10m0s'
        run: databricks jobs list

      - name: Run a databricks notebook
        env:
          DATABRICKS_HOST: https://dbc-11df7ca4-5026.cloud.databricks.com
          DATABRICKS_TOKEN: dapi2f98369b849c3790a880a6a9e4748434
        uses: databricks/run-notebook@v0.0.3
        with:
          local-notebook-path: .github/workflows/dabdemo_notebook.py
          new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "m5d.large"
           }

      
      
